// 1_Инструкция_по_размещению_вакансий_на_портале_Работа_России.pdf
export const INSTRUCTION_1 = 'f9LHodD0cOK2rRxPurmbFUAZHLLCP7dobVN2O8BiYPx0QgEhd6S0JhJD-C6mK5k7bBEOZldtaRfDdt1eOi5g'

// 2_Инструкция_по_подаче_заявления_на_портале_Работа_России.pdf
export const INSTRUCTION_2 = 'f9LHodD0cOLsRaV4D2IxEwDv9Lop0Ca3RowLAQEzqd9h0K0_hGxg5546UujFwo8hl4r7qrxitsuAw3atD_RI'

// 3_Инструкция_по_подаче_отчета_о_введении_режима_простоя_о_приостановке.pdf
export const INSTRUCTION_3 = 'f9LHodD0cOKrW8NN26ODrNjwVnk_nmMdgS8OzXXfHalx0jg7qmJ3a-n-obWLvRHYwweLGdXMig7vDCqo1m3l'

// 4_Инструкция_по_предоставлению_отчета_о_несостоятельности_банкротстве.pdf
export const INSTRUCTION_4 = 'f9LHodD0cOIqflWmAXqjzun7iIIGD8J1LONixS7igGl_jWYzYjfIuF3Dk44VRftH_HVhR5ugkB3Tr0PkxZuC'

// 5_Инструкция_по_предоставлению_отчета_о_сокращении_численности_сотрудников.pdf
export const INSTRUCTION_5 = 'f9LHodD0cOIm232urDnicmyyFZ1A_hlUsZqvUepophSoFRs-k4crlGbrc1Mwv__KXOxj2iPk6MlYe8PLOMjJ'

// 6_Инструкция_по_подаче_отчета_о_введении_режима_неполного_рабочего.pdf
export const INSTRUCTION_6 = 'f9LHodD0cOImmLUALBNIevzjk7INxRv8eRNDiZROViFpLQKfsRvv39CPSfaryqfa--O749HUEzoF7rJzlyGe'

// 7_Инструкция_по_подаче_отчета_о_выполнении_квоты_для_приема_на_работу.pdf
export const INSTRUCTION_7 = 'f9LHodD0cOJl5ExH5jC5oPpwZC0700aGF8TGNYKNB9U7BP_daKxmXT9lktAZxk7awi3JoOd9l0aVIP4cyooG'

// 8_Инструкция_по_подаче_отчета_о_дистанционной_удаленной_работе.pdf
export const INSTRUCTION_8 = 'f9LHodD0cOLO5RM679Bjo95Tu0uuafP3tMww9laFHiawxJ53ZXGe5yOK71UP_QYtGUpI8W7XNY_DThrBDpGV'

// 9_Инструкция_по_работе_с_откликами_соискателей.pdf
export const INSTRUCTION_9 = 'f9LHodD0cOK2gtf174SeefKh6_UoFgI0mBRdoN7Ld95pUdUGnAWSYH_2-8XavXfOO7fq7tFo9bJ8b4byMwT_'