# Generated by Django 6.0.1 on 2026-01-24 08:25

import django.db.models.deletion
import feedback_control_app.models.api_token
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование Api ключа')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('token', models.CharField(default=feedback_control_app.models.api_token.generate_api_token, max_length=100, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Api токен для бота',
                'verbose_name_plural': 'Api токены для ботов',
            },
        ),
        migrations.CreateModel(
            name='MaxBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование бота')),
                ('token', models.TextField(verbose_name='Токен бота')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('max_url', models.CharField(max_length=256, verbose_name='Ссылка на бота в максе')),
            ],
            options={
                'verbose_name': 'Макс бот',
                'verbose_name_plural': 'Макс боты',
            },
        ),
        migrations.CreateModel(
            name='CivilianRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('user_id', models.CharField(max_length=256, verbose_name='Идентификатор пользователя в Max')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Сообщение пользователя')),
                ('answer_status', models.BooleanField(default=False, verbose_name='Статус ответа')),
                ('api_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civilian_requests', to='feedback_control_app.apitoken', verbose_name='Api токен')),
                ('max_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civilian_requests', to='feedback_control_app.maxbot', verbose_name='Max бот')),
            ],
            options={
                'verbose_name': 'Обращение гражданина',
                'verbose_name_plural': 'Обращения граждан',
            },
        ),
        migrations.CreateModel(
            name='EmploeyrAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='Текст сотрудника')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('civilian_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emploeyr_answers', to='feedback_control_app.civilianrequest', verbose_name='Обращение гражданина')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emploeyr_answers', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ответ сотрудника на обращение',
                'verbose_name_plural': 'Ответы сотрудников на обращения',
            },
        ),
        migrations.CreateModel(
            name='EmploeyrAnswerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_grade', models.PositiveSmallIntegerField(choices=[(1, 'Полный провал'), (2, 'Неудовлетворительно'), (3, 'Удовлитворительно'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Степень удовлитворенности ответом')),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('ea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback_control_app.emploeyranswer', verbose_name='Ответ сотрудника ЦЗН')),
            ],
            options={
                'verbose_name': 'Оценка ответа сотрудника ЦЗН',
                'verbose_name_plural': 'Оценка ответов сотрудников ЦЗН',
            },
        ),
        migrations.AddField(
            model_name='apitoken',
            name='max_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='feedback_control_app.maxbot', verbose_name='Max бот'),
        ),
    ]
